batch_size: 1000
epochs: 10000
patience: 200

logdir: logs
run_name: test

model:
  _target_: models.mlp.MLP
  insize: 3 # left, right, operator_encoding
  hidden_sizes: [64]
  outsize: 1
  classification: true


train_dataset:
  # operator: "=="
  # operator: "<"
  operator: null
  _target_: dataset.dataset.InfixEquivalanceDataset
  encode_operator: true
  equal_p: 0.2
  _len: 10_000  # 10_000 /feels right/

dev_dataset:
  _target_: dataset.dataset.InfixEquivalanceDataset
  encode_operator: true
  equal_p: 0.2
  _len: 200

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.01
  # betas: [0.9, 0.999,]
  # eps: 1e-8
  # weight_decay: 1e-2
  # amsgrad: False
  # maximize: False
  # fused: Optional[bool]=None
